### ISSUE TITLE
Android crash when connecting.

### ISSUE THREAD

**Issue by DariusSG** [amphineko/yonagi#19]
Moved to new issue from #17.

The certificate created by PKI will cause my Samsung S23 with the latest update to crash and restart. Older versions are not affected.

The only alternative is to not validate the certificate, which is bad for security.

Apparently the cert CN is null? Crash does not happen on older android device and on IOS.

Android log via logcat
```
05-20 20:28:39.038 17596 17939 E AndroidRuntime: !@*** FATAL EXCEPTION IN SYSTEM PROCESS: WifiHandlerThread
05-20 20:28:39.038 17596 17939 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.android.server.wifi.util.CertificateSubjectInfo.commonName' on a null object reference in method 'void com.android.server.wifi.InsecureEapNetworkHandler.askForUserApprovalForCaCertificate()'
05-20 20:28:39.038 17596 17939 E AndroidRuntime: 	at com.android.server.wifi.InsecureEapNetworkHandler.askForUserApprovalForCaCertificate(InsecureEapNetworkHandler.java:667)
05-20 20:28:39.038 17596 17939 E AndroidRuntime: 	at com.android.server.wifi.InsecureEapNetworkHandler.startUserApprovalIfNecessary(InsecureEapNetworkHandler.java:399)
05-20 20:28:39.038 17596 17939 E AndroidRuntime: 	at com.android.server.wifi.ClientModeImpl$L2ConnectingState.processMessageImpl(ClientModeImpl.java:6230)
05-20 20:28:39.038 17596 17939 E AndroidRuntime: 	at com.android.server.wifi.RunnerState.processMessage(RunnerState.java:62)
05-20 20:28:39.038 17596 17939 E AndroidRuntime: 	at com.android.wifi.x.com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:1001)
05-20 20:28:39.038 17596 17939 E AndroidRuntime: 	at com.android.wifi.x.com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:819)
05-20 20:28:39.038 17596 17939 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-20 20:28:39.038 17596 17939 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
05-20 20:28:39.038 17596 17939 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
05-20 20:28:39.038 17596 17939 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

Server Certificate
```
Subject: CN=radius.dariussg.intra, O=DariusSG Intra Network
Issuer: CN=DariusSG Intra Network Root CA, O=DariusSG Intra Network
Validity: from 2024-05-12T08:20:33.000Z to 2025-05-12T08:20:33.000Z
-----BEGIN CERTIFICATE-----
MIICYzCCAemgAwIBAgIQcvqm8zKwxnbUgG+irPWjJTAKBggqhkjOPQQDAjB8MXow
QwYDVQQDHjwARABhAHIAaQB1AHMAUwBHACAASQBuAHQAcgBhACAATgBlAHQAdwBv
AHIAawAgAFIAbwBvAHQAIABDAEEwMwYDVQQKHiwARABhAHIAaQB1AHMAUwBHACAA
SQBuAHQAcgBhACAATgBlAHQAdwBvAHIAazAeFw0yNDA1MTIwODIwMzNaFw0yNTA1
MTIwODIwMzNaMGoxaDAxBgNVBAMeKgByAGEAZABpAHUAcwAuAGQAYQByAGkAdQBz
AHMAZwAuAGkAbgB0AHIAYTAzBgNVBAoeLABEAGEAcgBpAHUAcwBTAEcAIABJAG4A
dAByAGEAIABOAGUAdAB3AG8AcgBrMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE5i9F
9wIdD8eHAfXEExN0s8sHxDkW8b/mA3FI+DSyUGS2xZ7OsYQvR46AAukeyrDKEuFS
Q31OWYJAPzgkaRPbqWWFzz4ZQAEEYGjzqas/sky+cYrTXY3h/f6MFFVjUUqfo0Iw
QDAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIA4DAgBgNVHSUBAf8EFjAUBggr
BgEFBQcDAQYIKwYBBQUHAw4wCgYIKoZIzj0EAwIDaAAwZQIxAM5iJALcFo9JDUH3
13y+MDmJtN8o6YuJil74aXFqS5391pa3HcobxChMI0EqlIV3MAIwChr/WYsPBObX
ilj8kpoIiJE/zbDzZlm90locoqecVg/n7LvxyAWOXcpH4pHu8KTe
-----END CERTIFICATE-----
```

Root Certificate
```
Subject: CN=DariusSG Intra Network Root CA, O=DariusSG Intra Network
Issuer: CN=DariusSG Intra Network Root CA, O=DariusSG Intra Network
Validity: from 2024-05-12T08:20:11.000Z to 2034-05-10T08:20:11.000Z
-----BEGIN CERTIFICATE-----
MIICVjCCAdygAwIBAgIQFMHJ5bg3KGGIjv7Jo1y3CTAKBggqhkjOPQQDAjB8MXow
QwYDVQQDHjwARABhAHIAaQB1AHMAUwBHACAASQBuAHQAcgBhACAATgBlAHQAdwBv
AHIAawAgAFIAbwBvAHQAIABDAEEwMwYDVQQKHiwARABhAHIAaQB1AHMAUwBHACAA
SQBuAHQAcgBhACAATgBlAHQAdwBvAHIAazAeFw0yNDA1MTIwODIwMTFaFw0zNDA1
MTAwODIwMTFaMHwxejBDBgNVBAMePABEAGEAcgBpAHUAcwBTAEcAIABJAG4AdABy
AGEAIABOAGUAdAB3AG8AcgBrACAAUgBvAG8AdAAgAEMAQTAzBgNVBAoeLABEAGEA
cgBpAHUAcwBTAEcAIABJAG4AdAByAGEAIABOAGUAdAB3AG8AcgBrMHYwEAYHKoZI
zj0CAQYFK4EEACIDYgAEJ/3zWfk5PfYGd3Hrel/UAuB7DNEriIGwwFsQsVGFBI5q
kqRcccrWKibJjXvVYATMPPjTg406Yg+adGBVnmM/Qu4Vj6pZlfVj3zscC6FdKNrn
xn+6whOHxXGCmOj+g4pOoyMwITAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQE
AwIAhjAKBggqhkjOPQQDAgNoADBlAjATPkEyQud/YIQZb7QjDIQgsT4bLiA8BW0E
N/rXD1DhMM6o8To4/CyIVIR0Wx4dD18CMQDLETppEvu6vi0gBqUZIrl2vdFpX8Ww
5+GaHuuV0ehzNHg3LBg4vUJqJkqdBT/8NKQ=
-----END CERTIFICATE-----
```

p12 User Certificate (dariussg)   **Note, Please rename the file back to '.p12'. 
<details>
  <summary>Password</summary>
 neko
</details>

[3fe75e0ee79cf1fab866e941c0503368.txt](https://github.com/amphineko/yonagi/files/15377236/3fe75e0ee79cf1fab866e941c0503368.txt)

**Comment by DariusSG** [comment]
Weirdly enough, I works for my School WiFi which is using the same wpa-eap protocol.

**Comment by amphineko** [comment]
When I'm inspecting the server certificate you provided, the issuer is populated but in a weird string representation. This probably indicates the PKI didn't encode the string correctly. 

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            72:fa:a6:f3:32:b0:c6:76:d4:80:6f:a2:ac:f5:a3:25
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN=\x00D\x00a\x00r\x00i\x00u\x00s\x00S\x00G\x00 \x00I\x00n\x00t\x00r\x00a\x00 \x00N\x00e\x00t\x00w\x00o\x00r\x00k\x00 \x00R\x00o\x00o\x00t\x00 \x00C\x00A, O=\x00D\x00a\x00r\x00i\x00u\x00s\x00S\x00G\x00 \x00I\x00n\x00t\x00r\x00a\x00 \x00N\x00e\x00t\x00w\x00o\x00r\x00k
        Validity
            Not Before: May 12 08:20:33 2024 GMT
            Not After : May 12 08:20:33 2025 GMT
        Subject: CN=\x00r\x00a\x00d\x00i\x00u\x00s\x00.\x00d\x00a\x00r\x00i\x00u\x00s\x00s\x00g\x00.\x00i\x00n\x00t\x00r\x00a, O=\x00D\x00a\x00r\x00i\x00u\x00s\x00S\x00G\x00 \x00I\x00n\x00t\x00r\x00a\x00 \x00N\x00e\x00t\x00w\x00o\x00r\x00k
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                pub: 
                    04:e6:2f:45:f7:02:1d:0f:c7:87:01:f5:c4:13:13:
                    74:b3:cb:07:c4:39:16:f1:bf:e6:03:71:48:f8:34:
                    b2:50:64:b6:c5:9e:ce:b1:84:2f:47:8e:80:02:e9:
                    1e:ca:b0:ca:12:e1:52:43:7d:4e:59:82:40:3f:38:
                    24:69:13:db:a9:65:85:cf:3e:19:40:01:04:60:68:
                    f3:a9:ab:3f:b2:4c:be:71:8a:d3:5d:8d:e1:fd:fe:
                    8c:14:55:63:51:4a:9f
                ASN1 OID: secp384r1
                NIST CURVE: P-384
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Extended Key Usage: critical
                TLS Web Server Authentication, 1.3.6.1.5.5.7.3.14
    Signature Algorithm: ecdsa-with-SHA256
         30:65:02:31:00:ce:62:24:02:dc:16:8f:49:0d:41:f7:d7:7c:
         be:30:39:89:b4:df:28:e9:8b:89:8a:5e:f8:69:71:6a:4b:9d:
         fd:d6:96:b7:1d:ca:1b:c4:28:4c:23:41:2a:94:85:77:30:02:
         30:0a:1a:ff:59:8b:0f:04:e6:d7:8a:58:fc:92:9a:08:88:91:
         3f:cd:b0:f3:66:59:bd:d2:5a:1c:a2:a7:9c:56:0f:e7:ec:bb:
         f1:c8:05:8e:5d:ca:47:e2:91:ee:f0:a4:de
-----BEGIN CERTIFICATE-----
MIICYzCCAemgAwIBAgIQcvqm8zKwxnbUgG+irPWjJTAKBggqhkjOPQQDAjB8MXow
QwYDVQQDHjwARABhAHIAaQB1AHMAUwBHACAASQBuAHQAcgBhACAATgBlAHQAdwBv
AHIAawAgAFIAbwBvAHQAIABDAEEwMwYDVQQKHiwARABhAHIAaQB1AHMAUwBHACAA
SQBuAHQAcgBhACAATgBlAHQAdwBvAHIAazAeFw0yNDA1MTIwODIwMzNaFw0yNTA1
MTIwODIwMzNaMGoxaDAxBgNVBAMeKgByAGEAZABpAHUAcwAuAGQAYQByAGkAdQBz
AHMAZwAuAGkAbgB0AHIAYTAzBgNVBAoeLABEAGEAcgBpAHUAcwBTAEcAIABJAG4A
dAByAGEAIABOAGUAdAB3AG8AcgBrMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE5i9F
9wIdD8eHAfXEExN0s8sHxDkW8b/mA3FI+DSyUGS2xZ7OsYQvR46AAukeyrDKEuFS
Q31OWYJAPzgkaRPbqWWFzz4ZQAEEYGjzqas/sky+cYrTXY3h/f6MFFVjUUqfo0Iw
QDAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIA4DAgBgNVHSUBAf8EFjAUBggr
BgEFBQcDAQYIKwYBBQUHAw4wCgYIKoZIzj0EAwIDaAAwZQIxAM5iJALcFo9JDUH3
13y+MDmJtN8o6YuJil74aXFqS5391pa3HcobxChMI0EqlIV3MAIwChr/WYsPBObX
ilj8kpoIiJE/zbDzZlm90locoqecVg/n7LvxyAWOXcpH4pHu8KTe
-----END CERTIFICATE-----
```

However, based on the investigation in below, it seems unrelated to the issue we're having now.

---

From your logcat I suspect the following line is where the error occurs:

https://cs.android.com/android/_/android/platform/packages/modules/Wifi/+/6ac46ef90e32e323fb8b12807fd3bd0e420e0056:service/java/com/android/server/wifi/InsecureEapNetworkHandler.java;l=667;drc=9c4490cecdb83cf20d89af26bd99fc31cc5541c9

The function assumes `mPendingServerCertIssuerInfo` is non-null, which is populated in an earlier time:

https://cs.android.com/android/_/android/platform/packages/modules/Wifi/+/6ac46ef90e32e323fb8b12807fd3bd0e420e0056:service/java/com/android/server/wifi/InsecureEapNetworkHandler.java;l=312-317;drc=9c4490cecdb83cf20d89af26bd99fc31cc5541c9

Can you also confirm there is a log line saying `Cert has no valid issuer.`?

**Comment by amphineko** [comment]
> Weirdly enough, I works for my School WiFi which is using the same wpa-eap protocol.

Can you elaborate more on this?

**Comment by DariusSG** [comment]
> > Weirdly enough, I works for my School WiFi which is using the same wpa-eap protocol.
> 
> Can you elaborate more on this?

I was testing if it was a general bug or specific to this package.

> > Can you also confirm there is a log line saying Cert has no valid issuer.?
 
According to the logs, I appears that the weird string representation might be the cause.
```
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler: addPendingCertificate: SSID="<Redacted>" depth=0 certHash=d5e5b2efaae60433c5424e20a71f1e0fa5c0061e945e42a1f89750fb47d4bb7b current config="<Redacted>"WPA_EAP
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler: certificate content:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler: Certificate:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:     Data:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:         Version: 3 (0x2)
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:         Serial Number:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:              (Negative)58:43:d3:85:80:c0:a2:cc:0d:88:98:4d:87:06:c6:a8
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:     Signature Algorithm: ecdsa-with-SHA256
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:         Issuer: CN=\x00D\x00a\x00r\x00i\x00u\x00s\x00S\x00G\x00 \x00I\x00n\x00t\x00r\x00a\x00 \x00N\x00e\x00t\x00w\x00o\x00r\x00k\x00 \x00R\x00o\x00o\x00t, O=\x00D\x00a\x00r\x00i\x00u\x00s\x00S\x00G\x00 \x00I\x00n\x00t\x00r\x00a
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:         Validity
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:             Not Before: May 20 12:25:37 2024 GMT
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:             Not After : May 20 12:25:37 2025 GMT
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:         Subject: CN=\x00r\x00a\x00d\x00i\x00u\x00s\x00.\x00d\x00a\x00r\x00i\x00u\x00s\x00s\x00g\x00.\x00x\x00y\x00z, O=\x00D\x00a\x00r\x00i\x00u\x00s\x00S\x00G\x00 \x00I\x00n\x00t\x00r\x00a\x00 \x00N\x00e\x00t\x00w\x00o\x00r\x00k
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:         Subject Public Key Info:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:             Public Key Algorithm: id-ecPublicKey
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                 Public-Key: (P-384)
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                 pub:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                     04:b8:d0:53:34:48:b5:fa:81:0c:1c:f9:a2:66:f0:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                     ae:21:dd:89:a0:3a:a7:00:fb:b2:57:08:68:92:fe:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                     66:f0:93:5e:29:a5:e6:9d:27:84:e4:00:b6:0a:b1:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                     a9:9f:9d:88:71:05:72:0a:1f:e2:04:bb:f1:04:32:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                     e7:6c:16:27:2d:ac:60:70:40:53:15:28:2c:29:9b:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                     f3:71:78:e9:51:54:c5:cb:47:e7:72:2a:45:05:8b:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                     cc:22:99:1d:55:87:2f
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:         X509v3 extensions:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:             X509v3 Basic Constraints: critical
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                 CA:FALSE
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:             X509v3 Key Usage: critical
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                 Digital Signature, Non Repudiation, Key Encipherment
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:             X509v3 Extended Key Usage: critical
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:                 TLS Web Server Authentication, 1.3.6.1.5.5.7.3.14
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:     Signature Algorithm: ecdsa-with-SHA256
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:          30:64:02:30:6c:56:11:42:f2:89:32:af:63:63:24:70:50:20:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:          d2:a7:31:16:83:61:a1:ef:37:e1:02:b4:08:77:a0:aa:34:70:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:          4f:d9:df:a2:a2:59:31:3b:30:b5:aa:cc:4d:5e:05:72:02:30:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:          7f:b0:0f:c3:0d:6c:46:26:39:dd:6e:7f:b1:98:30:e4:51:d3:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:          67:61:9c:ed:f7:db:df:63:6a:41:9c:56:9e:d9:8d:d0:46:a4:
05-21 23:05:22.310  6577  6946 D InsecureEapNetworkHandler:          56:49:f4:cb:ab:d8:af:e6:76:c9:79:35
...
05-21 23:05:22.314  6577  6946 E CertificateSubjectInfo: Unable to unescape string: CN=\00r\00a\00d\00i\00u\00s\00.\00d\00a\00r\00i\00u\00s\00s\00g\00.\00x\00y\00z+O=\00D\00a\00r\00i\00u\00s\00S\00G\00 \00I\00n\00t\00r\00a\00 \00N\00e\00t\00w\00o\00r\00k
05-21 23:05:22.314  6577  6946 E InsecureEapNetworkHandler: Cert has no valid subject.
05-21 23:05:22.314  6577  6946 D WifiClientModeImpl: Cannot set pending cert.
05-21 23:05:22.318  6577  6946 D InsecureEapNetworkHandler: TOFU certificate chain:
05-21 23:05:22.318  6577  6946 D InsecureEapNetworkHandler: CN=\00r\00a\00d\00i\00u\00s\00.\00d\00a\00r\00i\00u\00s\00s\00g\00.\00x\00y\00z+O=\00D\00a\00r\00i\00u\00s\00S\00G\00 \00I\00n\00t\00r\00a\00 \00N\00e\00t\00w\00o\00r\00k
05-21 23:05:22.318  6577  6946 D InsecureEapNetworkHandler: CN=\00D\00a\00r\00i\00u\00s\00S\00G\00 \00I\00n\00t\00r\00a\00 \00N\00e\00t\00w\00o\00r\00k\00 \00R\00o\00o\00t+O=\00D\00a\00r\00i\00u\00s\00S\00G\00 \00I\00n\00t\00r\00a
...
05-21 23:05:22.328  6577  6946 I InsecureEapNetworkHandler: Server certificate chain validation succeeded, use Root CA
05-21 23:05:22.336  6577  6946 E AndroidRuntime: !@*** FATAL EXCEPTION IN SYSTEM PROCESS: WifiHandlerThread
```

Looks like it was unable to escape the subject and set the cert null
```
05-21 23:05:22.314  6577  6946 E CertificateSubjectInfo: Unable to unescape string: CN=\00r\00a\00d\00i\00u\00s\00.\00d\00a\00r\00i\00u\00s\00s\00g\00.\00x\00y\00z+O=\00D\00a\00r\00i\00u\00s\00S\00G\00 \00I\00n\00t\00r\00a\00 \00N\00e\00t\00w\00o\00r\00k
05-21 23:05:22.314  6577  6946 E InsecureEapNetworkHandler: Cert has no valid subject.
05-21 23:05:22.314  6577  6946 D WifiClientModeImpl: Cannot set pending cert.
```

**Comment by amphineko** [comment]
CN and other strings in Subject is encoded with BmpString, which could be the root cause.

https://github.com/amphineko/yonagi/blob/ff65e38b95585354e6edec59907136f08a73273d/packages/supervisor/src/pki/pkijs/utils.ts#L72

Switching to `PrintableString` or `UTF8String` might help.

**Comment by DariusSG** [comment]
> CN and other strings in Subject is encoded with `BmpString`, which could be the root cause.
> 
> https://github.com/amphineko/yonagi/blob/ff65e38b95585354e6edec59907136f08a73273d/packages/supervisor/src/pki/pkijs/utils.ts#L72
> 
> Switching to `PrintableString` or `UTF8String` might help.

Using UTF8String does not work.
However, Using PrintableString will allow it to process but when displayed, it shows
\<Common name\>, O=\<Org Name\>

More Investigation is required but for now, I'm switching to PrintableString as a temporary workaround.

**Comment by DariusSG** [comment]
Inspecting a known good certificate reveals this.
Known Good
![image](https://github.com/amphineko/yonagi/assets/39219301/817acf0d-9143-4844-9564-cdaacbd111a7)

Mine
![image](https://github.com/amphineko/yonagi/assets/39219301/f515e87a-f863-4400-b58a-753c72d9ba62)

As you can see, each subject is encoded in its own RDN and the string type is PrintableString.

**Comment by amphineko** [comment]
> Sidenote, Would it be possible to switch to using OpenSSL commands to generate certificate instead to ensure that certificate work properly for all devices?

I would prefer not to call OpenSSL by shell commands. However, I have considered migrating to OpenSSL node.js binding if necessarily.

> After looking at PKI.js, we would need to fork it to fix this minor display issue, which would be too much trouble.

By overriding ASN.1 serialization, it's possible to tweak the structure without forking. 

I have created #20 and please let me know if it works for you.

**Comment by DariusSG** [comment]
Testing #20, The following error came up
```
CertificateSubjectInfo: Unable to unescape string: O=<redacted>\ 
InsecureEapNetworkHandler: Cert has no valid issuer.
InsecureEapNetworkHandler: O=<redacted>,CN=<redacted>
InsecureEapNetworkHandler: O=<redacted>\ ,CN=<redacted>
```
Apparently there is an encoding error with the issuer subject.
Also, note that I have switched the code from using BmpString to PrintableString.
